<?php
header('Cache-Control: no-cache');
header('Content-type: application/json');
date_default_timezone_set("America/Los_Angeles");
$date = date("m-d-y");
$time = date("h:ia");
$address = $_SERVER['REMOTE_ADDR'];

$myObj->title = 'Hello, Perl!';
$myObj->heading = 'Hello, Perl!';
$myObj->message = 'This page was generated by Timo & Bradley with the Perl programming language';
$myObj->date = $date;
$myObj->time = $time;
$myObj->IP = $address;

$myJSON = json_encode($myObj);
print $myJSON;
?>