#!/usr/bin/python3

## Import modules for CGI handling
import cgi, cgitb
import socket
import os
import json
from datetime import date
from datetime import datetime

##  Headers
print("Cache-Control: no-cache")
print("Content-type:application/json\n")

# Current Time
current_date = datetime.today()

# IP address
hostname = os.environ['REMOTE_ADDR']

# construct json-like dictionary in python
json_data = {
                'title': 'Hello, Python!',
                'heading': 'Hello, Python!',
                'message': 'This page was generated by Timo & Bradley with the Python programming language',
                'time': current_date.now().strftime("%a %b %d %H:%M:%S %Y"),
                'IP': hostname
            }

# convert into JSON
data = json.dumps(json_data)

# print/return the json data
print(data)
